version: "3"
services:

  prometheus:
    image: prom/prometheus:v2.17.1
    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    network_mode: host
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data/:/prometheus/

#  pushgateway:
#    image: prom/pushgateway:latest
#    ports:
#      - 9091:9091

  grafana:
    image: grafana/grafana:6.7.2
    ports:
      - 3000:3000
    network_mode: host
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-password}
      - GF_LOG_MODE=console file
      - GF_LOG_LEVEL=info
    volumes:
      - ./grafana/logs:/var/log/grafana
      - ./grafana/data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards

#  alertmanager:
#    image: prom/alertmanager:latest
#    command: --config.file=/etc/alertmanager/alertmanager.yml
#    ports:
#      - 9093:9093
#    volumes:
#      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
